---

language: python
dist: xenial

matrix:
  include:
  - python: '3.7'
    env: RUN_FLAKE8=true

python:
- "3.7"
- "3.6"
- "2.7"
install:
- pip install -e .[develop]
script:
- test -n "$RUN_FLAKE8" || pytest
- test -z "$RUN_FLAKE8" || flake8 src/ tests setup.py
sudo: false
git:
  depth: 250
